### ISSUE TITLE
Ounce conversion

### ISSUE THREAD

**Issue by wooorm** [tmcw/flair#14]
While the ounce conversion is (probably) correct:

https://github.com/tmcw/flair/blob/05270b3727a1f8b4f384574461bbd6df3315dbd9/front/src/Quantity.elm#L67-L68

...iba mostly uses 15 and 30 ML increments in their recipes, leading to weird numbers in ounces.

Currently an aviation:

<img width="575" alt="Screen Shot 2020-03-19 at 7 56 44 am" src="https://user-images.githubusercontent.com/944406/77039917-39549e80-69b7-11ea-918c-5958eaadc65b.png">

Is measures in ounces as:

<img width="571" alt="Screen Shot 2020-03-19 at 7 56 52 am" src="https://user-images.githubusercontent.com/944406/77039937-41acd980-69b7-11ea-979c-45237a9d5d56.png">

...but using 30 ml == 1 oz may make the numbers prettier. 1.5, 0.5, 0.5.

**Comment by wooorm** [comment]
(this isn’t always the case though, there are some 10, 20, 50, etc ml’s defined, but those don’t look perfect in ounces currently either)

**Comment by tmcw** [comment]
Now using 30ml == 1oz
