### ISSUE TITLE
External links don’t seem to work

### ISSUE THREAD

**Issue by wooorm** [tmcw/flair#50]
Probably related to the internal routing; for me the links on the landing page (feedback, PRs welcome) don’t work anymore!

/cc @tmcw

**Comment by tmcw** [comment]
Weird, yeah! I think I messed this up when I switched to [application](https://package.elm-lang.org/packages/elm/browser/latest/Browser#application) from document and now the external links need to be approved by the `onUrlRequest` method. Can do, I'll look at it today!
